# Generated by Django 5.0 on 2024-01-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('Date', models.DateField()),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.article')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
